# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

stqa_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  _file: data.wikipedia
  _id_prefix:
